-- Dados iniciais (gerado por scripts/gen-seed-sql.ts)

insert into settings (id, data) values (1, '{"logo":"","logoDark":"","brandColor":"#FF5C00","inkColor":"#101828","roiUrl":"https://cibus.com.br/calculadora-roi","site":"cibus.com.br","contactEmail":"comercial@cibus.com.br","contactPhone":"","defaults":{"coverTitle":"Transforme cada compra em um *novo motivo para voltar*","coverSubtitle":"Proposta Comercial Cibus","proposalTitle":"Proposta Comercial Cibus Fuel","validity":"Proposta válida por 15 dias","implementationPrice":6000,"note":"Sem taxa por transação.","closingTitle":"Vamos transformar cada compra em um *novo motivo para voltar?*"}}'::jsonb) on conflict (id) do nothing;

insert into executives (id, name, email, phone, whatsapp, role, photo, active) values ('exec-gabriel-bettoni', 'Gabriel Bettoni', '', '', '', 'Executivo de Contas', '', true) on conflict (id) do nothing;
insert into executives (id, name, email, phone, whatsapp, role, photo, active) values ('exec-default', 'Executivo Cibus', 'comercial@cibus.com.br', '', '', 'Executivo de Contas', '', true) on conflict (id) do nothing;

insert into modules (id, name, description, category, default_price, active, sort_order) values ('mod-pontos', 'Pontos Cibus', 'Programa de pontos com regras flexíveis por produto e forma de pagamento.', 'Fidelidade', 249, true, 0) on conflict (id) do nothing;
insert into modules (id, name, description, category, default_price, active, sort_order) values ('mod-desconto', 'Desconto', 'Descontos exclusivos para clientes identificados.', 'Fidelidade', 249, true, 1) on conflict (id) do nothing;
insert into modules (id, name, description, category, default_price, active, sort_order) values ('mod-cashback', 'Cashback', 'Parte do valor da compra volta como saldo para a próxima visita.', 'Fidelidade', 249, true, 2) on conflict (id) do nothing;
insert into modules (id, name, description, category, default_price, active, sort_order) values ('mod-roleta', 'Roleta Premiada', 'Roleta da sorte com prêmios configuráveis a cada compra.', 'Engajamento', 249, true, 3) on conflict (id) do nothing;
insert into modules (id, name, description, category, default_price, active, sort_order) values ('mod-whatsapp', 'Comunicação WhatsApp', 'Disparos segmentados e jornadas automáticas via WhatsApp.', 'Comunicação', 149.9, true, 4) on conflict (id) do nothing;
insert into modules (id, name, description, category, default_price, active, sort_order) values ('mod-sorteio', 'Sorteio', 'Sorteios com números da sorte gerados automaticamente.', 'Engajamento', 79.9, true, 5) on conflict (id) do nothing;
insert into modules (id, name, description, category, default_price, active, sort_order) values ('mod-campanhas', 'Plataforma de Campanhas', 'Criação e gestão de campanhas promocionais.', 'Marketing', 79.9, true, 6) on conflict (id) do nothing;
insert into modules (id, name, description, category, default_price, active, sort_order) values ('mod-inteligencia', 'Inteligência Cibus', 'Indicadores e insights sobre o comportamento dos clientes.', 'Inteligência', 39.9, true, 7) on conflict (id) do nothing;
insert into modules (id, name, description, category, default_price, active, sort_order) values ('mod-regras', 'Regras de fidelidade', 'Regras por produto, dia, horário e perfil de cliente.', 'Fidelidade', 0, true, 8) on conflict (id) do nothing;
insert into modules (id, name, description, category, default_price, active, sort_order) values ('mod-raspadinha', 'Raspadinha', 'Raspadinha digital com prêmios instantâneos.', 'Engajamento', 0, true, 9) on conflict (id) do nothing;
insert into modules (id, name, description, category, default_price, active, sort_order) values ('mod-gamificacao', 'Gamificação', 'Missões, níveis e conquistas para aumentar a recorrência.', 'Engajamento', 0, true, 10) on conflict (id) do nothing;
insert into modules (id, name, description, category, default_price, active, sort_order) values ('mod-sms', 'SMS', 'Mensagens SMS transacionais e promocionais.', 'Comunicação', 0, true, 11) on conflict (id) do nothing;
insert into modules (id, name, description, category, default_price, active, sort_order) values ('mod-push', 'Push Notifications', 'Notificações no aplicativo do cliente.', 'Comunicação', 0, true, 12) on conflict (id) do nothing;
insert into modules (id, name, description, category, default_price, active, sort_order) values ('mod-segmentacao', 'Segmentação', 'Públicos por frequência, ticket e comportamento.', 'Marketing', 0, true, 13) on conflict (id) do nothing;
insert into modules (id, name, description, category, default_price, active, sort_order) values ('mod-promocoes', 'Promoções', 'Ofertas por produto, horário e público.', 'Marketing', 0, true, 14) on conflict (id) do nothing;
insert into modules (id, name, description, category, default_price, active, sort_order) values ('mod-dashboard', 'Dashboard', 'Painel com os principais indicadores da operação.', 'Inteligência', 0, true, 15) on conflict (id) do nothing;
insert into modules (id, name, description, category, default_price, active, sort_order) values ('mod-insights', 'Insights', 'Recomendações automáticas de ações.', 'Inteligência', 0, true, 16) on conflict (id) do nothing;
insert into modules (id, name, description, category, default_price, active, sort_order) values ('mod-ia', 'Inteligência Artificial', 'Modelos que antecipam churn e sugerem ofertas.', 'Inteligência', 0, true, 17) on conflict (id) do nothing;
insert into modules (id, name, description, category, default_price, active, sort_order) values ('mod-ranking', 'Ranking de frentistas', 'Engajamento da equipe com metas e ranking.', 'Operação', 0, true, 18) on conflict (id) do nothing;
insert into modules (id, name, description, category, default_price, active, sort_order) values ('mod-metas', 'Gestão de metas', 'Metas por posto, equipe e produto.', 'Operação', 0, true, 19) on conflict (id) do nothing;
insert into modules (id, name, description, category, default_price, active, sort_order) values ('mod-vouchers', 'Vouchers', 'Emissão e validação de vouchers.', 'Operação', 0, true, 20) on conflict (id) do nothing;
insert into modules (id, name, description, category, default_price, active, sort_order) values ('mod-paineis', 'Painéis gerenciais', 'Visão consolidada da rede para a gestão.', 'Operação', 0, true, 21) on conflict (id) do nothing;

insert into cases (id, name, company, segment, location, headline, description, logo, image, metric_1_name, metric_1_value, metric_2_name, metric_2_value, metric_3_name, metric_3_value, metric_4_name, metric_4_value, active) values ('case-tucuma', 'Posto Tucumã', 'Posto Tucumã', 'Posto de combustível', 'Tucumã — PA', 'Mais resultado com uma operação de fidelidade mais eficiente.', '<p>Com o programa de fidelidade Cibus, o posto passou a identificar seus clientes, criar campanhas segmentadas e incentivar a volta com recompensas a cada abastecimento.</p>', '', '', 'Ticket médio', 'R$ 58,50 → R$ 85,40', 'Aumento', '+45,98%', '', '', '', '', true) on conflict (id) do nothing;
insert into cases (id, name, company, segment, location, headline, description, logo, image, metric_1_name, metric_1_value, metric_2_name, metric_2_value, metric_3_name, metric_3_value, metric_4_name, metric_4_value, active) values ('case-rpb', 'Rede RPB', 'Rede RPB', 'Rede de postos', '', 'Fidelidade padronizada em toda a rede.', '', '', '', '', '', '', '', '', '', '', '', true) on conflict (id) do nothing;
insert into cases (id, name, company, segment, location, headline, description, logo, image, metric_1_name, metric_1_value, metric_2_name, metric_2_value, metric_3_name, metric_3_value, metric_4_name, metric_4_value, active) values ('case-baratao', 'Baratão da Construção', 'Baratão da Construção', 'MATCON', '', 'Recorrência no varejo de materiais de construção.', '', '', '', '', '', '', '', '', '', '', '', true) on conflict (id) do nothing;
