const fs = require("fs");
const src = fs.readFileSync(require("path").join(__dirname, "rumo.html"), "utf8");
const R = new Function(src.split('<script id="core">')[1].split("</script>")[0] + "; return RUMO;")();
const assert = require("assert");
const t = "2026-09-29"; // terça
const projects = [{ id: "p1", nome: "Prospecção SDR" }, { id: "p2", nome: "Estudos" }];
const q = (s) => R.parseQuick(s, projects, t);
let r = q("Ligar para Ana amanhã 14h #sdr p1");
assert.deepEqual([r.titulo, r.data, r.hora, r.projectId, r.prioridade], ["Ligar para Ana", "2026-09-30", "14:00", "p1", 1]);
r = q("Confirmar reuniões todo dia 16:30"); assert.deepEqual([r.titulo, r.recorrencia, r.data, r.hora], ["Confirmar reuniões", "daily", t, "16:30"]);
r = q("Revisão sexta #estudos"); assert.deepEqual([r.titulo, r.data, r.projectId], ["Revisão", "2026-10-02", "p2"]);
r = q("Pagar conta 05/10 p2"); assert.deepEqual([r.titulo, r.data, r.prioridade], ["Pagar conta", "2026-10-05", 2]);
r = q("Segunda reunião com o time"); assert.deepEqual([r.titulo, r.data], ["Segunda reunião com o time", null]);
r = q("Reunião com o time na segunda 10h"); assert.deepEqual([r.titulo, r.data, r.hora], ["Reunião com o time", "2026-10-05", "10:00"]);
r = q("Comprar pão #naoexiste"); assert.equal(r.titulo, "Comprar pão #naoexiste");
assert.equal(R.nextOccurrence("2026-10-02", "weekdays"), "2026-10-05");
assert.equal(R.nextOccurrence("2026-01-31", "monthly"), "2026-02-28");
const tpl = R.template("sdr", t);
const { project, tasks } = R.buildProject({ nome: tpl.nome, cor: tpl.cor, icone: tpl.icone, descricao: tpl.descricao }, tpl, undefined, t);
console.log("SDR:", project.stages.map((s) => s.nome + (s.final ? "✅" : "")).join(" → "), "|", tasks.length, "tarefas");
const rot = tasks.find((x) => x.recorrencia === "weekdays");
const { task: done, next } = R.setDone(rot, project, true, t);
assert.equal(done.stageId, project.stages.at(-1).id); assert.equal(next.data, "2026-09-30"); assert.equal(next.stageId, project.stages[0].id);
const again = R.setDone(done, project, false, t); assert.equal(again.task.stageId, project.stages[0].id); assert.equal(again.next, null);
const m = R.metrics([done, next], [project], { metaDiaria: 1 }, R.today());
console.log("metrics ok: doneToday", m.doneToday, "streak", m.streak);
const plan = R.normalizePlan({ tipo: "plano", mensagem: "x", plano: { etapas: ["a", "b"], rotina: [{ titulo: "r", recorrencia: "zzz", hora: "7:00" }], tarefas: [{ titulo: "t", emDias: "2", prioridade: 9 }] } });
assert.deepEqual([plan.rotina[0].recorrencia, plan.rotina[0].hora, plan.tarefas[0].prioridade, plan.tarefas[0].emDias], ["daily", "07:00", 4, 2]);
r = q("Revisar lei seca amanhã @revisão @Urgente #estudos"); assert.deepEqual([r.titulo, r.tags, r.projectId], ["Revisar lei seca", ["revisão", "Urgente"], "p2"]);
const proj = { tags: [{ id: "g1", nome: "Revisão", cor: "#2156e0" }] };
const rt = R.resolveTags(proj, ["revisao", "Urgente"]);
assert.equal(rt.ids[0], "g1"); assert.equal(rt.tags.length, 2); assert.equal(rt.tags[1].cor, R.TAG_COLORS[1]); assert.equal(rt.changed, true);
console.log("todos os testes do núcleo passaram");
